Elmboard/Areas/Users/ViewModels/ChangePasswordForUserViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Elmboard.Areas.Users.ViewModels
{
    public class ChangePasswordForUserViewModel
    {
        public string UserId { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

Elmboard/Areas/Users/Controllers/UserManageController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Elmboard.Models;
using System.Net;
using AutoMapper;
using Elmboard.Areas.Users.ViewModels;
using Elmboard.Core.Dtos;
using Elmboard.Core.Models;
using Elmboard.Persistence;

namespace Elmboard.Areas.Users.Controllers
{
    [Authorize(Roles = RoleName.SuperAdmin)]
    public class UserManageController : Controller
    {
        private ApplicationUserManager _userManager;

        public UserManageController()
        {
        }

        public UserManageController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: /Users/UserManage/ChangePasswordForUser/jhdjdkjdh-asuhhahf
        public ActionResult ChangePasswordForUser(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var applicationUser = new ElmboardDbContext().Users.Find(id);

            if (applicationUser == null)
            {
                return HttpNotFound();
            }

            var viewModel = new ChangePasswordForUserViewModel()
            {
                UserId = Mapper.Map<ApplicationUser, UserDto>(applicationUser).Id,
                FirstName = Mapper.Map<ApplicationUser, UserDto>(applicationUser).FirstName,
                Surname = Mapper.Map<ApplicationUser, UserDto>(applicationUser).Surname
            };

            return View(viewModel);
        }

        // POST: /Users/UserManage/ChangePasswordForUser
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ChangePasswordForUser(ChangePasswordForUserViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("ChangePasswordForUser", viewModel);
            };

            var code = await UserManager.GeneratePasswordResetTokenAsync(viewModel.UserId);
            var result = await UserManager.ResetPasswordAsync(viewModel.UserId, code, viewModel.NewPassword);
            if (result.Succeeded)
            {
                return RedirectToAction("Details", "Users", new { area = "Users", id = viewModel.UserId });
            }
            AddErrors(result);
            //return View("Edit", "Users", new { id = viewModel.UserId });
            return View();
        }

        #region Helpers

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        #endregion
    }
}

Elmboard/Areas/Users/Views/UserManage/ChangePasswordForUser.cshtml
@model Elmboard.Areas.Users.ViewModels.ChangePasswordForUserViewModel

@{
    ViewBag.Title = Model.FirstName + " " + Model.Surname;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-md-6">
    <div class="card">
        <div class="card-block">
            <div class="card-title-block">
                <h3 class="title mb-4">CHANGE PASSWORD</h3>
            </div>

            @using (Html.BeginForm("ChangePasswordForUser", "UserManage", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.UserId)
                @Html.HiddenFor(model => model.FirstName)
                @Html.HiddenFor(model => model.Surname)
                <hr />
                @Html.ValidationSummary("", new { @class = "has-error" })
                <div class="form-group">
                    @Html.LabelFor(m => m.NewPassword, new { @class = "control-label" })
                    @Html.PasswordFor(m => m.NewPassword, new { @class = "form-control boxed" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.ConfirmPassword, new { @class = "control-label" })
                    @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control boxed" })
                </div>
                <div class="form-group">
                    <input id="submit-password" type="submit" value="Save" class="btn btn-primary" />
                </div>
            }
        </div>
    </div>
</div>