Elmboard/Areas/Clients/Models/ClientAddressChange.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Elmboard.Areas.Clients.Models
{
    public class ClientAddressChange
    {
        public int Id { get; set; }

        public int ClientId { get; set; }

        public Client Client { get; set; }

        public string Address { get; set; }

        public string Postcode { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime DateMovedIn { get; set; }

    }
}

Elmboard/Areas/Clients/Models/ClientBusinessRelationship.cs
using Elmboard.Areas.Businesses.Models;
using Elmboard.Areas.Library.Models;

namespace Elmboard.Areas.Clients.Models
{
    public class ClientBusinessRelationship
    {
        public int ClientId { get; set; }
        public int BusinessId { get; set; }
        public byte RelationshipId { get; set; }

        public Client Client { get; set; }
        public Business Business { get; set; }
        public Relationship Relationship { get; set; }
    }
}

Elmboard/Areas/Clients/Models/ClientFile.cs
using Elmboard.Areas.Library.Models;
using System;
using System.ComponentModel.DataAnnotations;

namespace Elmboard.Areas.Clients.Models
{
    public class ClientFile
    {
        public int Id { get; set; }

        public int ClientId { get; set; }

        public Client Client { get; set; }

        public FileType FileType { get; set; }

        [Display(Name = "File type")]
        public byte FileTypeId { get; set; }

        public string FilePath { get; set; }

        [Required]
        [Display(Name = "File date")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime FileDate { get; set; }

        [Display(Name = "File description")]
        public string FileDescription { get; set; }
    }
}

Elmboard/Areas/Clients/ViewModels/ClientAddressChangesViewModel.cs
using Elmboard.Areas.Clients.Models;
using Elmboard.Core;
using System.Collections.Generic;

namespace Elmboard.Areas.Clients.ViewModels
{
    public class ClientAddressChangesViewModel
    {
        public int ClientId { get; }
        public IEnumerable<ClientAddressChange> ClientAddressChanges { get; }

        public ClientAddressChangesViewModel(int clientId, IUnitOfWork unitOfWork)
        {
            ClientId = clientId;
            ClientAddressChanges = unitOfWork.ClientAddressChanges.GetByClientId(clientId);
        }
    }
}

Elmboard/Areas/Clients/ViewModels/ClientBusinessRelationshipsViewModel.cs
using Elmboard.Core;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Elmboard.Areas.Clients.ViewModels
{
    public class ClientBusinessRelationshipsViewModel
    {
        public int ClientId { get; }
        public IEnumerable<SelectListItem> Clients { get; }
        public IEnumerable<SelectListItem> Businesses { get; }
        public IEnumerable<SelectListItem> Relationships { get; }
        public IEnumerable<RelatedBusinessesListItem> RelatedBusinessesList { get; }

        public ClientBusinessRelationshipsViewModel(int clientId, IUnitOfWork unitOfWork)
        {
            ClientId = clientId;
            RelatedBusinessesList = unitOfWork.ClientBusinessRelationships.GetRelatedBusinessesList(clientId);
            Clients = unitOfWork.Clients.GetSelectListItems();
            Businesses = unitOfWork.Businesses.GetSelectListItems();
            Relationships = unitOfWork.Relationships.GetSelectListItems();
        }
    }
}

Elmboard/Areas/Clients/Controllers/ClientAddressChangesController.cs
using Elmboard.Areas.Clients.Models;
using Elmboard.Areas.Clients.ViewModels;
using Elmboard.Core;
using Elmboard.Models;
using System;
using System.Web.Mvc;

namespace Elmboard.Areas.Clients.Controllers
{
    public class ClientAddressChangesController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;

        public ClientAddressChangesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: Clients/ClientAddressChanges/List/7
        public ActionResult List(int id)
        {
            return View("_ClientAddressChanges", new ClientAddressChangesViewModel(id, _unitOfWork));
        }

        // POST: Clients/ClientAddressChanges/Add
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(int clientId, string address, string postcode, DateTime dateMovedIn)
        {
            if (!ModelState.IsValid)
                return new HttpStatusCodeResult(500);

            if (_unitOfWork.ClientAddressChanges.IsExisting(clientId, address, postcode, dateMovedIn))
                return new HttpStatusCodeResult(500);

            _unitOfWork.ClientAddressChanges.Add(new ClientAddressChange
            {
                ClientId = clientId,
                Address = address,
                Postcode = postcode,
                DateMovedIn = dateMovedIn
            });

            _unitOfWork.Complete();

            //don't need a result since ajax is handling the outcome
            return new EmptyResult();
        }

        // POST: Clients/ClientAddressChanges/Delete/?changeId=7
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RoleName.Admin + ", " + RoleName.SuperAdmin)]
        public ActionResult Delete(int changeId)
        {
            _unitOfWork.ClientAddressChanges.Remove(_unitOfWork.ClientAddressChanges.GetById(changeId));
            _unitOfWork.Complete();

            //don't need a result since ajax is handling the outcome
            return new EmptyResult();

        }

    }

}

Elmboard/Areas/Clients/Controllers/ClientBusinessRelationshipsController.cs
using Elmboard.Areas.Clients.Models;
using Elmboard.Areas.Clients.ViewModels;
using Elmboard.Core;
using Elmboard.Models;
using System.Web.Mvc;

namespace Elmboard.Areas.Clients.Controllers
{
    public class ClientBusinessRelationshipsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ClientBusinessRelationshipsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: clients/ClientBusinessRelationships/List/5
        public ActionResult List(int id)
        {
            return View("_ClientBusinessRelationships", new ClientBusinessRelationshipsViewModel(id, _unitOfWork));
        }

        // POST: clients/ClientBusinessRelationships/Create/1/2/3
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Clients/ClientBusinessRelationships/Create/{clientId}/{businessId}/{relationshipId}")]
        public ActionResult Create(int clientId, int businessId, byte relationshipId)
        {
            if (!ModelState.IsValid)
                return RedirectToAction("Details", "Clients", new { area = "Clients", id = clientId });

            if (_unitOfWork.ClientBusinessRelationships.IsExisting(clientId, businessId, relationshipId))
                return new HttpStatusCodeResult(500);

            _unitOfWork.ClientBusinessRelationships.Add(new ClientBusinessRelationship
            {
                ClientId = clientId,
                BusinessId = businessId,
                RelationshipId = relationshipId
            });

            _unitOfWork.Complete();

            //don't need a result since ajax is handling the outcome
            return new EmptyResult();
        }

        // POST: clients/ClientBusinessRelationships/Delete/1/2/3
        [Route("Clients/ClientBusinessRelationships/Delete/{clientId}/{businessId}/{relationshipId}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = RoleName.Admin + ", " + RoleName.SuperAdmin)]
        public ActionResult Delete(int clientId, int businessId, byte relationshipId)
        {
            var clientBusinessRelationship = _unitOfWork.ClientBusinessRelationships
                .GetClientBusinessRelationship(clientId, businessId, relationshipId);
            _unitOfWork.ClientBusinessRelationships.Remove(clientBusinessRelationship);
            _unitOfWork.Complete();

            //don't need a result since ajax is handling the outcome
            return new EmptyResult();
        }

    }

}

Elmboard/Areas/Clients/Controllers/ClientFilesController.cs
using Elmboard.Areas.Clients.Models;
using Elmboard.Areas.Clients.ViewModels;
using Elmboard.Core;
using System;
using System.IO;
using System.Web.Mvc;

namespace Elmboard.Areas.Clients.Controllers
{
    [Authorize]
    public class ClientFilesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ClientFilesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        //GET /clients/clientfiles/List/1
        public ActionResult List(int id)
        {
            return PartialView("_ClientFiles", new ClientFilesViewModel(id, _unitOfWork));
        }


        //POST /clients/clientfiles/uploadfile?clientId=1
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult UploadFile(int clientId)
        {
            var file = Request.Files[0];
            if (file.ContentLength > 10000000) //10MB
                return new HttpStatusCodeResult(500);

            Directory.CreateDirectory(Path.Combine(Server.MapPath("~/ClientFiles/"), clientId.ToString()));
            var path = Path.Combine(Server.MapPath("~/ClientFiles/" + clientId + "/"), Path.GetFileName(file.FileName));
            file.SaveAs(path);

            _unitOfWork.ClientFiles.Add(new ClientFile
            {
                ClientId = clientId,
                FileTypeId = byte.Parse(Request.Form.Get("fileType")),
                FileDate = DateTime.Parse(Request.Form.Get("fileDate")),
                FileDescription = Request.Form.Get("fileDescription"),
                FilePath = path
            });

            _unitOfWork.Complete();

            return new EmptyResult();
        }

    }
}

Elmboard/Controllers/Api/BusinessesController.cs
using AutoMapper;
using Elmboard.Areas.Businesses.Models;
using Elmboard.Core;
using Elmboard.Core.Dtos;
using Elmboard.Models;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web.Http;
using System.Web.Http.Description;

namespace Elmboard.Controllers.Api
{
    [Authorize]
    public class BusinessesController : ApiController
    {
        private readonly IUnitOfWork _unitOfWork;

        public BusinessesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: api/Businesses
        public IEnumerable<BusinessDto> GetBusinesses()
        {
            return _unitOfWork.Businesses.GetAll().Select(Mapper.Map<Business, BusinessDto>);
        }

        // GET: api/Businesses/5
        [ResponseType(typeof(BusinessDto))]
        public IHttpActionResult GetBusiness(int id)
        {
            var business = _unitOfWork.Businesses.GetById(id);

            if (business == null)
                return NotFound();

            return Ok(Mapper.Map<Business, BusinessDto>(business));
        }

        // PUT: api/Businesses/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutBusiness(int id, BusinessDto businessDto)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            if (id != businessDto.Id)
                return BadRequest();

            Mapper.Map(businessDto, _unitOfWork.Businesses.GetById(id));

            try
            {
                _unitOfWork.Complete();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (_unitOfWork.Businesses.GetById(id) != null)
                    return Conflict();

                throw;
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Businesses
        [ResponseType(typeof(BusinessDto))]
        public IHttpActionResult PostBusiness(BusinessDto businessDto)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            var business = Mapper.Map<BusinessDto, Business>(businessDto);
            _unitOfWork.Businesses.Add(business);

            try
            {
                _unitOfWork.Complete();
            }
            catch (DbUpdateException)
            {
                if (_unitOfWork.Businesses.GetById(business.Id) != null)
                    return Conflict();

                throw;
            }

            return CreatedAtRoute("DefaultApi", new { id = business.Id }, businessDto);
        }

        // DELETE: api/Businesses/5
        [ResponseType(typeof(Business))]
        [Authorize(Roles = RoleName.Admin + ", " + RoleName.SuperAdmin)]
        public IHttpActionResult DeleteBusiness(int id)
        {
            var business = _unitOfWork.Businesses.GetById(id);

            if (business == null)
                return NotFound();

            var clientRelationshipsToDelete = _unitOfWork.ClientBusinessRelationships.GetByBusinessId(id);

            foreach (var r in clientRelationshipsToDelete)
                _unitOfWork.ClientBusinessRelationships.Remove(r);

            var businessAddressChangesToDelete = _unitOfWork.BusinessAddressChanges.GetByBusinessId(id);

            foreach (var c in businessAddressChangesToDelete)
                _unitOfWork.BusinessAddressChanges.Remove(c);

            _unitOfWork.Businesses.Remove(business);
            _unitOfWork.Complete();

            return Ok(business);
        }
    }
}

Elmboard/Controllers/Api/ClientsController.cs
using AutoMapper;
using Elmboard.Areas.Clients.Models;
using Elmboard.Core;
using Elmboard.Core.Dtos;
using Elmboard.Models;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web.Http;
using System.Web.Http.Description;

namespace Elmboard.Controllers.Api
{
    [Authorize]
    public class ClientsController : ApiController
    {

        private readonly IUnitOfWork _unitOfWork;

        public ClientsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: api/Clients
        public IEnumerable<ClientDto> GetClients()
        {
            return _unitOfWork.Clients.GetAll().Select(Mapper.Map<Client, ClientDto>);
        }

        // GET: api/Clients/5
        [ResponseType(typeof(ClientDto))]
        public IHttpActionResult GetClient(int id)
        {
            var client = _unitOfWork.Clients.GetById(id);
            if (client == null)
                return NotFound();

            return Ok(Mapper.Map<Client, ClientDto>(client));
        }

        // PUT: api/Clients/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutClient(int id, ClientDto clientDto)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            if (id != clientDto.Id)
                return BadRequest();

            Mapper.Map(clientDto, _unitOfWork.Clients.GetById(id));

            try
            {
                _unitOfWork.Complete();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (_unitOfWork.Clients.GetById(id) != null)
                    return NotFound();

                throw;
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Clients
        [ResponseType(typeof(ClientDto))]
        public IHttpActionResult PostClient(ClientDto clientDto)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            var client = Mapper.Map<ClientDto, Client>(clientDto);
            _unitOfWork.Clients.Add(client);

            try
            {
                _unitOfWork.Complete();
            }
            catch (DbUpdateException)
            {
                if (_unitOfWork.Clients.GetById(client.Id) != null)
                    return Conflict();

                throw;

            }

            return CreatedAtRoute("DefaultApi", new { id = client.Id }, clientDto);
        }

        // DELETE: api/Clients/5
        [ResponseType(typeof(Client))]
        [Authorize(Roles = RoleName.Admin + ", " + RoleName.SuperAdmin)]
        public IHttpActionResult DeleteClient(int id)
        {
            var client = _unitOfWork.Clients.GetById(id);
            if (client == null)
                return NotFound();

            var clientRelationshipsToDelete =
                _unitOfWork.Client1Client2Relationships.GetClientsRelationshipsBothWays(id);

            foreach (var r in clientRelationshipsToDelete)
                _unitOfWork.Client1Client2Relationships.Remove(r);

            var businessRelationshipsToDelete = _unitOfWork.ClientBusinessRelationships.GetByClientId(id);

            foreach (var r in businessRelationshipsToDelete)
                _unitOfWork.ClientBusinessRelationships.Remove(r);

            var clientAddressChangesToDelete = _unitOfWork.ClientAddressChanges.GetByClientId(id);

            foreach (var c in clientAddressChangesToDelete)
                _unitOfWork.ClientAddressChanges.Remove(c);

            _unitOfWork.Clients.Remove(client);
            _unitOfWork.Complete();

            return Ok(client);
        }
    }
}

Elmboard/Areas/Clients/Views/Shared/_ClientAddressChanges.cshtml
@using Elmboard.Models
@model Elmboard.Areas.Clients.ViewModels.ClientAddressChangesViewModel

<div class="card-block">
    <div class="card-title-block">
        <h3 class="title mb-4">ADDRESS HISTORY</h3>
    </div>
    <div class="table-responsive">
        <table id="client-address-changes-table" class="table table-hover">
            <thead>
                <tr>
                    <th>Address</th>
                    <th>Date moved in</th>
                    @{
                        if (User.IsInRole(RoleName.Admin) || User.IsInRole(RoleName.SuperAdmin))
                        {
                            <th>Actions</th>
                        }
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.ClientAddressChanges)
                {
                <tr>
                    <td>@item.Address, @item.Postcode</td>
                    <td>@item.DateMovedIn.ToString("dd/MM/yyyy")</td>
                    @{
                        if (User.IsInRole(RoleName.Admin) || User.IsInRole(RoleName.SuperAdmin))
                        {
                            <td>
                                <a href="#" data-address-change-id="@item.Id" class="js-delete">Delete</a>
                            </td>
                        }
                    }
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Elmboard/Areas/Clients/Views/Shared/_ClientBusinessRelationships.cshtml
@using Elmboard.Models
@model Elmboard.Areas.Clients.ViewModels.ClientBusinessRelationshipsViewModel

<div class="card-block">
    <div class="card-title-block">
        <h3 class="title mb-4">RELATIONSHIPS</h3>
        <h5 class="title">Businesses</h5>
    </div>
    <div class="table-responsive">
        <table id="relationships-businesses-table" class="table table-hover">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Relationship</th>
                    @{
                        if (User.IsInRole(RoleName.Admin) || User.IsInRole(RoleName.SuperAdmin))
                        {
                            <th>Actions</th>
                        }
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.RelatedBusinessesList)
                {
                <tr>
                    <th scope="row">@item.BusinessIdListItem</th>
                    <td>@Html.ActionLink(@item.BusinessNameListItem, "Details", "Businesses", new { area = "Businesses", id = item.BusinessIdListItem }, null)
                    <td>@item.RelationshipNameListItem</td>
                    @{
                        if (User.IsInRole(RoleName.Admin) || User.IsInRole(RoleName.SuperAdmin))
                        {
                            <td>
                                <a href="#" data-relationship-client-id="@Model.ClientId"
                                   data-relationship-business-id="@item.BusinessIdListItem"
                                   data-relationship-id="@item.RelationshipIdListItem"
                                   class="js-delete">Delete</a>
                            </td>
                        }
                    }

                </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="card-title-block">
        <h3 class="title my-4">New Relationship</h3>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationMessageFor(m => m.RelatedBusinessesList, "", new { @class = "has-error mb-3" })
        <div class="form-group">
            <div class="table-responsive">
                <table class="table">
                    <tr class="form-group">
                        <th class="relationship-dropdowns-header">Business</th>
                        <td>@Html.DropDownList("businessId", Model.Businesses, "", new { @class = "form-control boxed my-2 select2" })</td>
                    </tr>
                    <tr class="form-group">
                        <th class="relationship-dropdowns-header">Relationship Type</th>
                        <td>@Html.DropDownList("businessRelationshipId", Model.Relationships, "", new { @class = "form-control boxed my-2 select2"})</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="form-group">
            <input id="submit-business-relationship" type="button" value="Save" class="btn btn-primary" />
        </div>
    }
</div>

Elmboard/Areas/Clients/Views/Shared/_ClientClientRelationships.cshtml
@using Elmboard.Models
@model Elmboard.Areas.Clients.ViewModels.ClientRelationshipsViewModel

<div class="card-block">
    <div class="card-title-block">
        <h3 class="title mb-4">RELATIONSHIPS</h3>
        <h5 class="title">Clients</h5>
    </div>
    <div class="table-responsive">
        <table id="relationships-clients-table" class="table table-hover">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Telephone</th>
                    <th>E-mail</th>
                    <th>Relationship</th>
                    @{
                        if (User.IsInRole(RoleName.Admin) || User.IsInRole(RoleName.SuperAdmin))
                        {
                            <th>Actions</th>
                        }
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.RelatedClientsList)
                {
                <tr>
                    <th scope="row">@item.ClientIdListItem</th>
                    <td>@Html.ActionLink(@item.ClientNameListItem, "Details", "Clients", new { area = "Clients", id = item.ClientIdListItem }, null)
                    <td>@item.ClientTelephoneListItem</td>
                    <td><a href="mailto:@item.ClientEmailListItem">@item.ClientEmailListItem</a></td>
                    <td>@item.RelationshipNameListItem</td>
                    @{
                        if (User.IsInRole(RoleName.Admin) || User.IsInRole(RoleName.SuperAdmin))
                        {
                            <td>
                                <a href="#" data-relationship-client1-id="@Model.ClientId"
                                   data-relationship-client2-id="@item.ClientIdListItem"
                                   data-relationship-id="@item.RelationshipIdListItem"
                                   class="js-delete">Delete</a>
                            </td>
                        }
                    }

                </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="card-title-block">
        <h3 class="title my-4">New Relationship</h3>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationMessageFor(m => m.RelatedClientsList, "", new { @class = "has-error mb-3" })
        <div class="form-group">
            <div class="table-responsive">
                <table class="table">
                    <tr class="form-group">
                        <th class="relationship-dropdowns-header">Client</th>
                        <td>@Html.DropDownList("clientId", Model.Clients, "", new { @class = "form-control boxed my-2 select2" })</td>
                    </tr>
                    <tr class="form-group">
                        <th class="relationship-dropdowns-header">Relationship Type</th>
                        <td>@Html.DropDownList("clientRelationshipId", Model.Relationships, "", new { @class = "form-control boxed my-2 select2"})</td>
                    </tr>
                </table>
            </div>
        </div>

        <div class="form-group">
            <input id="submit-client-relationship" type="button" value="Save" class="btn btn-primary" />
        </div>
    }
</div>

Elmboard/Areas/Clients/Views/Shared/_ClientFiles.cshtml
@using Elmboard.Models
@model Elmboard.Areas.Clients.ViewModels.ClientFilesViewModel


<div class="card-block">
    <div class="card-title-block">
        <h3 class="title mb-4">FILES</h3>
        <h5 class="title">Client Files</h5>
    </div>
    <div class="table-responsive">
        <table id="client-files-table" class="table table-hover">
            <thead>
            <tr>
                <th>Name</th>
                <th>Type</th>
                <th>Date</th>
                @{
                    if (User.IsInRole(RoleName.Admin) || User.IsInRole(RoleName.SuperAdmin))
                    {
                        <th>Actions</th>
                    }
                }
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model.ClientFilesList)
            {
                <tr><td colspan="4"><b>@item.FileDescriptionListItem</b></td></tr>
                <tr>
                    <td>@Path.GetFileName(item.FileNameListItem)</td>
                    <td>@item.FileTypeNameListItem</td>
                    <td>@item.FileDateListItem.ToString("dd/MM/yyyy")</td>
                    @{
                        if (User.IsInRole(RoleName.Admin) || User.IsInRole(RoleName.SuperAdmin))
                        {
                            <td>
                                <a href="#" data-file-id="@item.ClientFileIdListItem" class="js-delete">Delete</a>
                            </td>
                        }
                    }
                </tr>

            }
            </tbody>
        </table>
    </div>
    <div class="card-title-block">
        <h3 class="title my-4">Upload New File</h3>
    </div>

    <div class="col-8">

        @using (Html.BeginForm("UploadFile", "ClientFiles", new {clientId = @Model.ClientId}, FormMethod.Post, new { id="client-files-form", enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

            <input id="choose-client-file" name="file" type="file" value="Choose File" class="inputfile" />
            <label id="choose-client-file-label" for="choose-client-file" class="btn btn-primary my-4">Choose a file...</label>

            <div class="form-group">
                <div class="table-responsive">
                    <table class="table">
                        <tr id="file-name-container" class="form-group d-none">
                            <th class="mt-1">Name</th>
                            <th id="chosen-file-name"></th>
                        </tr>

                        <tr class="form-group">
                            <th class="mt-1">Type</th>
                            <td>@Html.DropDownList("typeId", Model.FileTypes, "", new { @class = "form-control boxed my-1 select2" })</td>
                        </tr>
                        <tr class="form-group">
                            <th class="mt-1">Date</th>
                            <td><input type="text" id="FileDate" name="FileDate" class="form-control boxed my-1 datepicker" placeholder="File date..." required /></td>
                        </tr>
                        <tr class="form-group">
                            <th class="mt-1">Description</th>
                            <td><textarea rows="2" id="FileDescription" name="FileDescription" class="form-control boxed my-1" placeholder="File Description..."></textarea></td>
                        </tr>
                    </table>
                </div>
            </div>
            <div>
                <span class="form-group">
                    <input id="upload-client-file" type="button" value="Upload" class="btn btn-primary" />
                </span>
            </div>
        }
    </div>
</div>