Elmboard/Areas/Help/Controllers/HelpController.cs
using Elmboard.Models;
using System.Web.Mvc;

namespace Elmboard.Areas.Help.Controllers
{
    public class HelpController : Controller
    {
        // GET: Help/Help
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = RoleName.SuperAdmin)]
        public ActionResult _HelpAdmin()
        {
            return PartialView();
        }

        public ActionResult _HelpClientsBusinesses()
        {
            return PartialView();
        }

        public ActionResult _HelpCustomize()
        {
            return PartialView();
        }

        public ActionResult _HelpRelationships()
        {
            return PartialView();
        }

        public ActionResult _HelpSearch()
        {
            return PartialView();
        }
    }
}

Elmboard/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Elmboard.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            return View();
        }       
    }
}

Elmboard/Views/Dashboard/Index.cshtml
@using Microsoft.AspNet.Identity
@using System.Security.Claims


@{    
    var identity = (ClaimsIdentity)User.Identity;
    var userFirstName = " " + identity.FindFirstValue(ClaimTypes.GivenName);
    if (userFirstName == " ")
    {
        ViewBag.Title = "Hello!";
    }
    else
    {
        ViewBag.Title = "Hello" + userFirstName + "!";
    }

    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="col-md-6">
    <div class="card">
        <div class="card-block">
            <div>
                <p><strong>Elmboard</strong> is a basic CRM (<i>Client Relations Manager</i>) web application for accountants.</p>
                <p>You can use it to store and search your clients personal and business details.</p>
                <p>The application was designed based on an in-house application of a real-life accountancy firm, successfuly used for many years in daily work with clients.</p>
                <p>More options and expanded functionalities are in the works!</p>
                <p class="mt-2">To help you get started, there is a @Html.ActionLink("tutorial", "Index", "Help", new { area = "Help" }, null) you can read.</p>
            </div>
        </div>
    </div>
</div>